docs/README.md
Resolves issue https://github.com/AGiXT/Interactive/issues/12
=> add videos and correct logo

package.json
The easiest way I could find to use 3000 port without changing more stuff than necessary
=> local dev env port

components/interactive/Chat/Message/Markdown/CodeBlock.tsx
Changes visible to users:
Internal changes:
=> Fix Codeblock Theme

components/interactive/Chat/Chat.tsx, lib/sdk.ts
=> Fix conversation import content display

components/interactive/Selectors/ChainSelector.tsx, components/interactive/Selectors/CommandSelector.tsx, components/interactive/Selectors/PromptSelector.tsx, components/interactive/Settings/chain/ChainStep.tsx, components/interactive/Settings/chain/ChainSteps.tsx, components/interactive/hooks/useChain.ts
This PR addresses issue #48 by fixing chain step population issues. It updates state handling, ensures correct prop passing in selectors, and improves type validation. Now, agent names and prompt names populate correctly when modifying a chain.
Changes visible to users:
Internal changes:
=> Fix: Ensure Chain Steps Populate Correctly

app/settings/abilities/page.tsx, components/idiot/appwrapper/NavMain.tsx, components/interactive/Settings/abilities.tsx, components/interactive/Settings/index.tsx
This pull request includes significant changes to the settings pages, specifically adding a new `Abilities` page and modifying the navigation and structure to accommodate this addition. The most important changes include creating a new `AbilitiesPage` component, updating the navigation to include the abilities section, and refactoring existing components to support the new functionality.
* [`app/settings/abilities/page.tsx`](diffhunk://#diff-9b51603a5057f8e8b9e503bcb8345a21842f3173adbfc1f08618e3e57136f955R1-R10): Added a new `AbilitiesPage` component that includes the `SidebarPage` layout and the `Abilities` component.
* [`components/idiot/appwrapper/NavMain.tsx`](diffhunk://#diff-33e0094578791c5d0768868fbf9cf22786da29558b82cd084318dd279ca11d7aL223-L232): Updated the navigation to include …
=> ~Split Abilities and Extensions tab to two separate pages (fix for issue #52)

components/idiot/appwrapper/NavMain.tsx
This PR addresses the issue where the "Team Management" menu item should not be visible for users with `role_id > 2`. Additionally, it includes performance optimizations and code cleanup for the `NavMain` component.
Resolves #61 
Wallet address: GQjfQcP4pTWNqs421DE63du27yDubBNa5GyC386sNHfF
- **Visibility Fix**: Updated the `Team Management` item in the `items` array to use `roleThreshold: 2`. The item is now only visible for users when `company.role_id <= roleThreshold`.
- **Optimization**: Replaced `useState` and `useEffect` with `useMemo` for computing the menu items, reducing unnecessary re-renders and improving performance.
- **Code Cleanup**: Moved visibility logic directly into the filter step, eliminating the `visible` prop and simplifying the data flow (filter then map instead of …
=> Restrict Team Management menu item visibility and optimize NavMain

app/user/login/page.tsx, app/user/manage/page.tsx, app/user/register/page.tsx
Fix register page styling and simplify auth pages further
=> Fix register page styling and simplify auth pages further

app/page.tsx, components/auth/OAuth.tsx, components/auth/Subscribe.tsx, components/layout/NavMain.tsx, docs-agixt/5-Reference/2-Cryptocurrency.md, docs-agixt/5-Reference/3-Social Media.md, tsconfig.json
Add documentation, clean up paths
This pull request includes several changes to the `app/page.tsx`, `components/auth/Subscribe.tsx`, `components/auth/OAuth.tsx`, `components/layout/NavMain.tsx`, and documentation files to update the subscription component, navigation items, and add new documentation for cryptocurrency and social media.
* [`app/page.tsx`](diffhunk://#diff-6efdf509a785a0658b2e31a8c33d298de14321d9672179370e99cc76241c1eb0L6-R6): Replaced `Subscribe` component with `PricingTable` component. [[1]](diffhunk://#diff-6efdf509a785a0658b2e31a8c33d298de14321d9672179370e99cc76241c1eb0L6-R6) [[2]](diffhunk://#diff-6efdf509a785a0658b2e31a8c33d298de14321d9672179370e99cc76241c1eb0L51-R51)
* [`components/auth/Subscribe.tsx`](diffhunk://#diff-25d6c967489c4ddd16ce98f4d92007fb8767cdd9fe19bad0f …
=> Add documentation, clean up paths

components/layout/NavMain.tsx
Add loading to side menu, auto expand documentation if no logged in user.
This pull request includes several changes to the `NavMain` component in `components/layout/NavMain.tsx` to improve its functionality and user experience. Key changes involve adding a loading state, checking for JWT existence on mount, and enhancing the logic for item filtering and active state determination.
* Added `useEffect` and `useState` hooks to check for JWT existence once the component mounts. [[1]](diffhunk://#diff-a72ce7f49f7c8962165aaeb757d1ad93082899c0c5f89529a066c136b4c9d179R37) [[2]](diffhunk://#diff-a72ce7f49f7c8962165aaeb757d1ad93082899c0c5f89529a066c136b4c9d179L240-R301)
* Introduced a loading state to display a spinner until all necessary data is ready.
* Modified the item filtering logic to …
=> Add loading to side menu, auto expand documentation if no logged in user

app/settings/page.tsx, components/conversation/Message/MarkdownBlock.tsx
Add Solana Wallet UI
- Fixes #112
=> Add Solana Wallet UI

app/globals.css, components/command-menu/group/quick-actions.tsx, components/command-menu/group/theme.tsx, components/layout/themes.tsx
Remove broken colorblind mode. It doesn't work and doesn't really need to.
=> Remove broken colorblind mode

app/NavMenuItems.tsx, app/docs/page.tsx, middleware.tsx
=> fix readme

tests/FrontEnd.py
This PR implements the `handle_logout` and `handle_login` functions in `FrontEnd.py` to properly test the logout and login workflows as requested in issue #66. The implementation has been designed to be robust with multiple fallback approaches since UI interactions can sometimes be fragile in automated testing.
- Implemented `handle_logout` function with multiple approaches to find and click the logout button
- Implemented `handle_login` function to handle the complete login workflow with MFA
- Added proper error handling, logging, and screenshots for each step
- Ensured compatibility with the existing test automation framework
The implementation was tested with the AGiXT Interactive UI and successfully:
- Logs out the user using the dropdown menu in the user profile
- Logs in with saved …
=> Issue--66 | feat: Implement login/logout test workflows

tests/FrontEnd.py
Closes #68
This PR adds implementations for two automated UI test functions in `FrontEnd.py`:
- `handle_update_user`: Tests user profile updates, including changing last name and timezone settings
- `handle_invite_user`: Tests the team invitation workflow
- Both functions use Playwright for browser automation
- Added robust element selection with multiple fallback strategies
- Included thorough error handling and diagnostics
- Maintained consistency with existing test patterns
Tested both functions on the local development environment with success:
- Profile updates are properly detected and applied
- Team invitations are sent and verified in the pending list
Automated screenshots are taken at each step of the process for documentation and debugging.
The implementation is designed to be …
=> Issue-68 | feat: Implement user update and team invitation test workflows

components/conversation/Message/Actions.tsx
[Screencast from 2025-03-28 01-01-54.webm](https://github.com/user-attachments/assets/e50b6c98-fed3-4974-99e5-f889a23fd0d5)
=> Fork instantly

app/layout.tsx, app/page.tsx, app/settings/abilities/page.tsx, app/settings/page.tsx, app/team/page.tsx, app/user/login/page.tsx, components/auth/Subscribe.tsx, components/command-menu/index.tsx, components/layout/AuthCard.tsx, components/layout/SidebarMain.tsx, components/ui/sidebar.tsx, package-lock.json, package.json
Resolves Issue #124: Implement responsive design for mobile and tablet devices
This PR implements comprehensive responsive design across the application, ensuring optimal user experience on mobile and tablet devices. We've used the `react-responsive` library to detect screen sizes and conditionally render appropriate layouts and components.
- Added `react-responsive` package for media queries and device detection
- Implemented responsive layouts for all major pages and components
- Modified text sizes, spacing, and UI elements for mobile devices
- Added mobile-specific navigation and sidebar controls
- Optimized forms and data tables for smaller screens
- Fixed sidebar behavior on mobile devices
Here's a simple example of how we're using the `react-responsive` library throughout the …
=> Issue-124 Fix - Fix Pages for Mobile View

app/settings/chains/page.tsx, app/settings/page.tsx, components/interactive/useAgent.ts
=> Fix public wallet display

tests/FrontEnd.py
See Title
From
```python
await asyncio.sleep(1)
await self.page.wait_for_load_state("domcontentloaded", timeout=30000) #30sec is Default
result = await action_function()
await self.page.wait_for_load_state("domcontentloaded", timeout=30000) #30sec is Default
await asyncio.sleep(1)
```
To
```python
await asyncio.sleep(5)
await self.page.wait_for_load_state("domcontentloaded", timeout=90000)
result = await action_function()
await self.page.wait_for_load_state("domcontentloaded", timeout=90000)
await asyncio.sleep(5)
```
=> Adjusted Playwright Test Timers

app/settings/page.tsx
API call reduction on settings page
=> API call reduction on settings page

app/user/login/page.tsx
This PR adds toast notifications to improve the user experience when sending email verification codes during the multi-factor authentication process.
Closes #135
- Added the `useToast` hook from our existing toast notification system
- Implemented toast notifications during the email verification code sending process:
- Shows a "Sending" toast while the request is in progress
- Shows a "Sent" toast once complete, regardless of API response
- Used a graceful error handling approach that ensures users always receive clear feedback
- Added responsive sizing to accommodate mobile screens
- Improves user feedback during the authentication process
- Provides a more polished user experience
- Handles network errors gracefully without confusing the user
- Maintains a consistent UI pattern with …
=> Add Toast Notifications to Login MFA Email Flow

app/layout.tsx, app/page.tsx, app/settings/abilities/page.tsx, app/settings/page.tsx, app/team/page.tsx, app/user/login/page.tsx, components/auth/Subscribe.tsx, components/command-menu/index.tsx, components/layout/AuthCard.tsx, components/layout/SidebarMain.tsx, components/ui/sidebar.tsx, package-lock.json
Revert mobile breaking refactor
=> Revert mobile breaking refactor

app/settings/training/page.tsx
Resolves Issue #140
This PR introduces significant improvements to the Training page, focusing on enhanced URL learning capabilities and overall user experience:
- Added a dedicated "Learn From URL" section
- Introduced configurable URL learning parameters:
- Number of chunks
- Character length per chunk
- Implemented dynamic URL processing with progress tracking
- Added input validation for URL learning
- Enhanced error handling and user feedback
- Added more granular control over URL content extraction
- Improved progress tracking for both document uploads and URL learning
- Added placeholder and default values for URL learning configuration
- Added new state variables for URL learning:
- `learnUrl`
- `urlChunks`
- `urlCharacterLength`
- `isLearningUrl`
- `urlProgress`
- Created …
=> Issue-140 Feat(training): Add URL learning with advanced configuration options

app/settings/training/page.tsx
=> Nuke Useless Stuff

app/NavMenuItems.tsx, app/settings/prompts/page.tsx
=> Add prompt library docs

app/settings/chains/page.tsx, components/interactive/useChain.ts, lib/sdk.ts
Add chain description to chains
=> Add chain description to chains

app/settings/abilities/page.tsx
This PR improves the command toggle mechanism in the Abilities page with more robust state management, loading indicators, and user feedback.
- Added advanced state tracking for command toggles
- Implemented loading states for individual commands
- Added toast notifications for successful and failed command updates
- Introduced a safe toggle mechanism to prevent concurrent toggle attempts
- Improved error handling and user experience
- Introduced `commandStates` to track:
- Loading state
- Original command state
- Current command state
- Created `safeToggleCommand` to prevent multiple concurrent toggle attempts
- Added loading spinner for commands during toggle
- Implemented toast notifications:
- Success toast when a command is enabled/disabled
- Error toast for failed toggle attempts
- …
=> Improve Command Toggle Functionality with Advanced State Management

app/settings/abilities/page.tsx, components/conversation/conversation.tsx
This PR addresses the issues with renaming conversations by implementing a more robust and user-friendly renaming process.
- Rename Conversation button was not working correctly
- No visible name change after renaming
- Renaming did not work when sidebar was minimized
- Implemented a comprehensive renaming workflow
- Added logic to automatically expand sidebar when renaming
- Ensured proper state management during rename process
- Added input validation to prevent empty conversation names
- Enhanced sidebar interaction for rename functionality
- Added state tracking for sidebar expansion and renaming mode
- Implemented automatic sidebar opening when rename is initiated
- Improved handling of conversation name changes
- Added `wasExpanded` state to manage sidebar state
- Created more …
=> Fix Renaming a Conversation

components/conversation/conversation.tsx, components/conversation/input/chat-input.tsx
Resolves Issue #27: Move import conversation to chat input
This PR moves the import conversation functionality from the ChatSidebar component to the ChatBar component, making it conditionally visible only when the chat is empty. This improves the user experience by presenting the import option at a contextually relevant time.
- Removed import functionality from ChatSidebar component
- Added ImportConversation component to chat-input.tsx
- Made the import option conditionally render only when conversation is empty
- Added dialog UI for importing via file upload
- Enhanced error handling for the import process
- Improved styling and keyboard interactions
- Verified import functionality works correctly in the new location
- Confirmed it only appears when the conversation is empty
- Tested …
=> Move import conversation to chat input

components/interactive/useUser.ts, docs-agixt/5-Reference/4-User Tems.md
This PR fixes https://github.com/Josh-XT/AGiXT/issues/1421
- Added basic user terms, required by X OAuth configuration when requesting the user's email.
- Removed minimum length validation for lastName to avoid schema errors when the value is an empty string.
Changes visible to users:
Internal changes:
- [ x **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ x My change works!
=> Fix X OAuth login

app/page.tsx
=> Better landing page

components/layout/SidebarMain.tsx
Fix #170 
This pull request enhances error handling, loading states, and user feedback in the `SidebarMain` component. Key updates include adding retry logic for data fetching, improving loading and error states in the UI, and introducing a fallback option for navigation when errors occur.
* Added retry logic for data fetching in both `AgentSelector` and `NavMain` components, with a maximum of three retries and a delay of one second between retries. (`[[1]](diffhunk://#diff-b878a836bbef0380f34fee8dbfee5f0dd3746ac687c61b7ab57a817fcbc00626R62-R125)`, `[[2]](diffhunk://#diff-b878a836bbef0380f34fee8dbfee5f0dd3746ac687c61b7ab57a817fcbc00626L289-R394)`)
* Introduced a loading timeout mechanism in `NavMain` to prevent indefinite loading states, with a fallback UI for partial navigation when …
=> Fix issue 170

middleware.tsx
=> Clear JWT on 401 and 403

components/layout/SidebarMain.tsx, tests/FrontEnd.py
=> Improve tests reliability

components/layout/SidebarMain.tsx, tests/FrontEnd.py
Add demo for abilities
This pull request makes significant updates to the `tests/FrontEnd.py` file to enhance test navigation consistency and introduce new functionality for handling feature demonstrations. The changes primarily focus on standardizing the starting point for tests, adding a helper method for navigation, and implementing new test scenarios like extensions and abilities configuration.
* Added the `navigate_to_chat_first` helper method to ensure all tests start at the chat interface for consistent navigation.
* Updated multiple test cases (`handle_chat`, `handle_commands_workflow`, `handle_mandatory_context`, `handle_email`, etc.) to use the new navigation helper for consistency. [[1]](diffhunk://#diff-c13688be573dc0ede4bb03a516becaeae2311c2a34da80ee8558e716ebebcccbL626-R630) …
=> Add demo for abilities

app/tasks/page.tsx
Changes visible to users:
Internal changes:
=> Revamp Tasks Conversations and requires title and description

app/settings/page.tsx, components/interactive/useAgent.ts
Add rename company agent, fix solana keys on agent settings page
This pull request focuses on improving the `AgentSettings` component and related functionality by enhancing data handling, introducing new features, and improving maintainability. The most significant changes include restructuring the `agentData` object, adding a handler for renaming company agents, and refining error handling and logging.
* Updated `agentData` to include a nested `agent` property, requiring changes in multiple locations to access agent-specific data (e.g., `agentData?.agent?.settings` instead of `agentData?.settings`). This improves consistency and clarity in accessing nested data. [[1]](diffhunk://#diff-e441de59e2b06b106855d24f892efc380ce6620dfe254590fd5debb910467ce6L87-R87) …
=> Add rename company agent, fix solana keys on agent settings page
